swtor_basics:

   North       : [ Button: '&'                ]
   North       : [ Button: '&'                ]
   East        : [ Button: é                  ]
   South       : [ Button: '"'                ]
   West        : [ Button: "'"                ]

   DPadUp      : [ Button: z                  ]
   DPadDown    : [ Button: s                  ]
   DPadLeft    : [ Button: q                  ]
   DPadRight   : [ Button: d                  ]

   RightThumb  : [ Toggle: mouse_right        ]
   RightStickX : [ MouseX: 3.0                ]
   RightStickY : [ MouseY: 3.0                ]

   LeftStickX  : [ Axis2Button: [ q, d, 0.6 ] ]
   LeftStickY  : [ Axis2Button: [ s, z, 0.1 ] ]
